name: 'Prettier: Format Code'

on:
  push:
  pull_request:
    branches:
      - master

permissions: write-all

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prettierfy code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          commit_message: '[format] Prettierfy code'
